### ISSUE TITLE
marker锚点在不同级别下不正确

### ISSUE THREAD

**Issue by fuzhenn** [deyihu/maptalks-awesome-markers#1]
![image](https://user-images.githubusercontent.com/13678919/36909402-cd0bd9fe-1e78-11e8-8333-ad482a1b4f5c.png)

放大地图后：

![image](https://user-images.githubusercontent.com/13678919/36909408-d2e31040-1e78-11e8-9ea5-8d14fe583a21.png)

**Comment by deyihu** [comment]
@fuzhenn [fix icon position is diffent on diffent zoom](https://github.com/deyihu/maptalks-awesome-markers/commit/cee1550934ebd7653dfd3a2111fa4de592b7d5bf)

**Comment by deyihu** [comment]
@fuzhenn 其实如果是以icon的左上角作参考的是对的，只不过这个图标弄的像定位图标，感官上是错的
